In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('analysis_data/most_keluhan_akulaku_superset_presto_hanmm 1769063889.csv')
df.info()

C:\Users\ozy.prazuganda\AppData\Local\Temp\ipykernel_9004\676855241.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('analysis_data/most_keluhan_akulaku_superset_presto_hanmm 1769063889.csv')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 137739 entries, 0 to 137738
Data columns (total 56 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   company                          137739 non-null  object
 1   Aplication                       137739 non-null  object
 2   UID                              136519 non-null  object
 3   UserName                         137737 non-null  object
 4   Phone Number                     137739 non-null  object
 5   Ticket Type                      137739 non-null  object
 6   Ticket complaint_type            130967 non-null  object
 7   Ticket ID                        137739 non-null  int64
 8   Ticket NO                        137739 non-null  object
 9   Ticket Status                    137739 non-null  object
 10  Ticket Valid                     137739 non-null  object
 11  TICKET CLOSED REASON             14985 non-null   object
 12  Ticket Source                    137739 non-null  object
 13  Complain to OJK                  137739 non-null  int64
 14  Case_category_path               137739 non-null  object
 15  Case Category                    137739 non-null  object
 16  enable                           137739 non-null  int64
 17  Category1                        137739 non-null  object
 18  Category2                        118588 non-null  object
 19  Category3                        117120 non-null  object
 20  forward_trace 1:转排查 0:没转         137739 non-null  int64
 21  Bussiness Name                   137739 non-null  object
 22  Priority(LOW,MIDDLE,HIGH,URGE;)  137739 non-null  object
 23  append_times                     137739 non-null  int64
 24  urge_times                       137739 non-null  int64
 25  Cases Description                137545 non-null  object
 26  Next Follow up Time              246 non-null     object
 27  Previous Assigner                15146 non-null   float64
 28  Processor Name                   15146 non-null   object
 29  Ticket Current Comment           107876 non-null  object
 30  Created By (UID)                 137739 non-null  float64
 31  Create_user_name                 137739 non-null  object
 32  Ticket Creating Time             137739 non-null  object
 33  Update Time                      137739 non-null  object
 34  first_response time              118460 non-null  object
 35  ticket close_time                136646 non-null  object
 36  ticket_create_clsoe_day          137739 non-null  float64
 37  is_over_five_days                137739 non-null  object
 38  first_response_over_24h          137739 non-null  object
 39  first_update_user_id             12119 non-null   float64
 40  first_update_user_name           12119 non-null   object
 41  first_update_time                12119 non-null   object
 42  Update UID                       9231 non-null    float64
 43  ticket_closed_cs_uid             108646 non-null  float64
 44  ticket_closed_cs_name            108646 non-null  object
 45  ticket_closed_email              108646 non-null  object
 46  choice                           3104 non-null    float64
 47  choice_label                     3104 non-null    object
 48  if_has_record(HANG_OUT)          137739 non-null  int64
 49  ticket finish_time               11130 non-null   object
 50  ticket first finish_time         11130 non-null   object
 51  ticket finish_byuser             11130 non-null   object
 52  ticket first finish_byuser       11130 non-null   object
 53  finished_duration (/h)           11119 non-null   float64
 54  total_pending_duration (/h)      4246 non-null    float64
 55  total_onhold_duration (/h)       3178 non-null    float64
dtypes: float64(10), int64(7), object(39)
memory usage: 58.8+ MB

In [16]:
df

,company,Aplication,UID,UserName,Phone Number,Ticket Type,Ticket complaint_type,Ticket ID,Ticket NO,Ticket Status,...,choice,choice_label,if_has_record(HANG_OUT),ticket finish_time,ticket first finish_time,ticket finish_byuser,ticket first finish_byuser,finished_duration (/h),total_pending_duration (/h),total_onhold_duration (/h)
0,Akulaku,ASI,2047779496.0,AL$$_1_QYx1iYrgq2vQhr3kLu6P0xeL/Z/KTgHYxg8zbTD...,AL$$_1_jYmcIPTTJP6Johmz9g6+ZIlbZD4rNuoKDpSKeML...,SERVICE_COMMENT,consult,22530351,"02000120251203004260,",Closed,...,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Akulaku,ASI,9082822.0,AL$$_1_YvE9VC9y5DTGQ91hmaCn878NeEBZpCQpcQ8rZm3...,AL$$_1_jYmcIPTTJP6Johmz9g6+ZIlbZD4rNuoKDpSKeML...,SERVICE_COMMENT,consult,22533584,"02000120251203007492,",Closed,...,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Akulaku,ASI,2021752327.0,AL$$_1_LTIqFqyOWGquTwtQ1Ir8/ji0m+ewnsYBdgKHQaU...,AL$$_1_jYmcIPTTJP6Johmz9g6+ZIlbZD4rNuoKDpSKeML...,SERVICE_COMMENT,consult,22609157,"02000120251213001352,",Closed,...,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Akulaku,ASI,2041154732.0,AL$$_1_ldShcV+2sjDla4yaNL7xFelf58SqgY7rnGVbeVb...,AL$$_1_jYmcIPTTJP6Johmz9g6+ZIlbZD4rNuoKDpSKeML...,SERVICE_COMMENT,consult,22609379,"02000120251213001574,",Closed,...,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Akulaku,ASI,9130203.0,AL$$_1_dDE6rTgm7nE/WZuzstxhQQoTw5RoAEpefjxXgFh...,AL$$_1_jYmcIPTTJP6Johmz9g6+ZIlbZD4rNuoKDpSKeML...,SERVICE_COMMENT,consult,22727270,"02000120251231000079,",Closed,...,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137734,Akulaku,ASI,2053029653,AL$$_1_dxaU8BPsiQ6n9QPevhlNKHeMTkTNjaalpveFgQz...,AL$$_1_jYmcIPTTJP6Johmz9g6+ZIlbZD4rNuoKDpSKeML...,SERVICE_COMMENT,consult,22646910,"02000120251218005726,",Closed,...,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
137735,Akulaku,ASI,2005199905,AL$$_1_MHJl+HKe0sFc6A4kzlbRvJMpOpTeawIXzRYX0Gs...,AL$$_1_jYmcIPTTJP6Johmz9g6+ZIlbZD4rNuoKDpSKeML...,SERVICE_COMMENT,consult,22644942,"02000120251218003758,",Closed,...,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
137736,Akulaku,ASI,102526328,AL$$_1_GYS2jR1NCt3UkeqtxVroklB7/gELMimDmux7WkQ...,AL$$_1_jYmcIPTTJP6Johmz9g6+ZIlbZD4rNuoKDpSKeML...,TICKET,complaint,22645959,"02000120251218004775,",Closed,...,NaN,NaN,1,1/14/2026 10:10,1/14/2026 10:10,Ferdiansyah,Ferdiansyah,0.002176,NaN,618.581678
137737,Akulaku,ASI,2040817994,AL$$_1_jDZMvlWs3IFYwB10eN4Mbis+EeMwpUwkio8KwiW...,AL$$_1_jYmcIPTTJP6Johmz9g6+ZIlbZD4rNuoKDpSKeML...,SERVICE_COMMENT,consult,22645192,"02000120251218004008,",Closed,...,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
137738,Akulaku,ASI,19777377,AL$$_1_lEW6U7PLddYl9YGr4bpnwM5j6d1Dhte/vO+qCTV...,AL$$_1_jYmcIPTTJP6Johmz9g6+ZIlbZD4rNuoKDpSKeML...,TICKET,complaint,22613976,"02000120251214000307,",Closed,...,NaN,NaN,0,12/15/2025 13:42,12/15/2025 13:42,Muhammad Yunus Dwi Krismantyo,Muhammad Yunus Dwi Krismantyo,0.002138,NaN,NaN

In [11]:
df.iloc[:,[15,17,18,19]]

,Case Category,Category1,Category2,Category3
0,Kendala Pengajuan Pinjaman,Bugs,Pengajuan Pinjaman,Kendala Pengajuan Pinjaman
1,Resi Invalid,3 Party Group Chat,Pengiriman,Resi Invalid
2,Permintaan Kode Pembayaran,Dana Cicil (Large Loan),Collection,Permintaan Kode Pembayaran
3,Gagal Pengajuan,PDL,Pengajuan Pinjaman,Gagal Pengajuan
4,Informasi Terkait Limit Pinjaman,PDL,Pengajuan Pinjaman,Informasi Terkait Limit Pinjaman
...,...,...,...,...
137734,Gagal Pengajuan,PDL,Pengajuan Pinjaman,Gagal Pengajuan
137735,Informasi Umum,Informasi Umum & Feedback,Feedback,Informasi Umum
137736,Pembayaran Belum Masuk Sistem,PDL,Pembayaran & Tagihan (Pinjaman),Pembayaran Belum Masuk Sistem
137737,Gagal Pengajuan,PDL,Pengajuan Pinjaman,Gagal Pengajuan
137738,Informasi Terkait Proses Pengajuan,Dana Cicil (Large Loan),Pengajuan Pinjaman,Informasi Terkait Proses Pengajuan

In [ ]:
df['Case Category'].value_counts()

Case Category
Gagal Pengajuan                                   22379
Transfer Call/Chat to AFI                         11746
Informasi Terkait Pembayaran Pinjaman              9937
Permintaan Kode Pembayaran                         6384
Informasi Terkait Tagihan                          4881
                                                  ...
Opsi Pembayaran Tidak Muncul/Kendala - Danamon        1
Double Pembayaran - Down Payment (DP)                 1
Informasi Terkait Promo Produk Tunggal                1
Special case Dana Cicil                               1
Pembatalan Akulaku Protection Gadget                  1
Name: count, Length: 229, dtype: int64

In [23]:
df['Category1'].value_counts()

Category1
PDL                                  52676
Dana Cicil (Large Loan)              24560
Informasi Umum & Feedback            14844
Transfer Call/Chat to AFI            11746
3 Party Group Chat                    5361
Pengkinian Data                       4807
Merchant Online                       4622
Transfer Chat Ke ASI - E-Commerce     3459
Dana Flexi                            3198
Issue Refund Ticket New               3122
Case Email                            2085
Produk Virtual & Voucher              1901
Bugs                                  1750
Promo/Event                           1018
Transfer Chat Ke ASI - Loan            682
Keamanan Akun                          654
Complaint Case New                     518
Loan                                   448
Tiket Pesawat                          108
Refund (Tier 2)                         98
CS Merchant Case                        56
Official Store                          16
Fraud E-Commerce                         4
Cari Danaku                              4
Merchant Loan                            1
Global Buy                               1
Name: count, dtype: int64

In [24]:
df['Category2'].value_counts()

Category2
Pengajuan Pinjaman                       40073
Pembayaran & Tagihan (Pinjaman)          25751
Collection                               12219
Spam                                      6375
Incomplete Details                        5685
                                         ...
Merchant Offline                             2
Akulaku Goods Protection                     1
Hapus Denda                                  1
Double Pembayaran - Down Payment (DP)        1
Promo Produk Tunggal                         1
Name: count, Length: 64, dtype: int64

In [ ]:
df['Category3'].value_counts()

Category3
Gagal Pengajuan                                   22379
Informasi Terkait Pembayaran Pinjaman              9937
Permintaan Kode Pembayaran                         6384
Informasi Terkait Tagihan                          4881
Informasi Terkait Proses Pengajuan                 4516
                                                  ...
Opsi Pembayaran Tidak Muncul/Kendala - Danamon        1
Pinjaman/Cash Loan/PDL/PayLater/OpenPay               1
Informasi Terkait Promo Produk Tunggal                1
Special case Dana Cicil                               1
Pembatalan Akulaku Protection Gadget                  1
Name: count, Length: 210, dtype: int64

: