In [1]:
import pandas as pd

In [ ]:
text = """
▶
Alfacart - Pembayaran tidak sinkron
0
▶
Alfacart - Status cancel tidak sinkron
0
▶
Apakah bisa belanja di toko offline
0
▶
Bhinneka - Status cancel tidak sinkron
0
▶
BL - Status cancel tidak sinkron
0
▶
Blibli - Status cancel tidak sinkron
0
▶
Blibli - Status pembayaran tidak sinkron
0
▶
BodyBigSize - Status cancel tidak sinkron
0
▶
Pembayaran tagihan aplikasi DANA
0
▶
Faspay - Transaksi
0
▶
HITA - Status cancel tidak sinkron
0
▶
Ipay88 - Status cancel tidak sinkron
0
▶
Ipaymu - Status cancel tidak sinkron
0
▶
Kendala openpay
0
▶
Lazada Paylater/Masalah pembayaran
0
▶
Lazada Paylater/transaksi
0
▶
Lazada Paylater/Kendala pembelian
0
▶
LAZADA paylater refund
0
▶
MYHARTONO - Status cancel tidak sinkron
0
▶
NCR Sport - Status cancel tidak sinkron
0
▶
Shopee - status cancel tidak sinkron
0
▶
Shopee - Status pembayaran tidak sinkron
0
▶
tiket.com- Status cancel tidak sinkron
0
▶
Blibli - Batas waktu retur barang
0
▶
Blibli - Cara pengiriman pengembalian barang
0
▶
Blibli - Estimasi pengiriman
0
▶
Blibli - Estimasi proses retur
0
▶
Blibli - Ongkos kirim retur
0
▶
Blibli - Pembatalan pesanan yang sudah terbayar
0
▶
Blibli - Pengembalian barang ditolak
0
▶
Blibli - Pesanan belum diterima
0
▶
Blibli - Pesanan menunggu pengiriman
0
▶
Blibli - Pesanan yang diterima jumlah tidak sesuai/rusak/tidak sesuai deskripsi
0
▶
Blibli - Pesanan yang diterima rusak/pecah saat pengiriman
0
▶
Waktu penerimaan produk setelah pembayaran berhasil
0
▶
JD.ID - Pembatalan pesanan yang sudah terbayar
0
▶
JD.ID - Pesanan belum diterima
0
▶
JD.ID - Pesanan menunggu pengiriman
0
▶
JD.ID - Pesanan yang diterima jumlah tidak sesuai/rusak/tidak sesuai deskripsi
0
▶
JD.ID - Pesanan yang diterima rusak/pecah saat pengiriman
0
▶
Merchant yang mendukung fitur Scan
0
▶
Transaksi Tiktok sudah terbatalkan, dana sudah dikembalikan, tetapi tagihan pada akulaku masih muncul
0
▶
Pembayaran Klik Indomaret gagal
0
▶
Tidak dapat menemukan akses untuk klaim Akulaku Elite Card
0
▶
Dapat menemukan akses untuk klaim namun gagal saat diklaim
0
▶
Bertanya apakah akan menerima kartu fisik setelah mengklaim kartu Akulaku Elite Card
0
▶
Limit Akulau Elite Card lebih rendah dari limit kredit Akulaku Paylater
0
▶
Cara melakukan cicilan dengan Akulaku Elite Card
0
▶
Nominal tagihan tidak sesuai dengan nominal transaksi Akulaku Elite Card (nominal tagihan lebih tinggi dari nominal yang dipakai untuk transaksi)
0
▶
Bunga yang dikenakan untuk transaksi dengan Akulaku Elite Card
0
▶
Bayar tagihan Akulaku Elite Card di aplikasi bank mitra (BNI)
0
▶
Platform yang mendukung pembayaran Elite Card
0
▶
Nominal denda Akulaku Elite Card
0
▶
Pengguna dapat menemukan akses untuk klaim Akulaku Elite Card namun tidak dapat mengaktifkan Elite Card
0
▶
Akulaku Elite Card tidak dapat digunakan untuk transaksi
0
▶
Terdapat transaksi Elite Card yang bukan dilakukan oleh pengguna
0
▶
Sudah melakukan refund/cancel transaksi di merchant eksternal, namun limit kredit di akun Akulaku tidak dipulihkan
0
▶
Tidak dapat menggunakan voucher Elite Card
0
▶
User melakukan pembayaran tagihan Elite Card sebanyak 2 kali atau lebih
0
▶
Pembayaran untuk tagihan Elite Card belum masuk sistem
0
▶
Bertanya apa itu Akulaku In-Store Installment
0
▶
Denda tagihan Akulaku In-Store Installment
0
▶
Cara pembayaran tagihan Akulaku In-Store Installment
0
▶
Jumlah limit Akulaku In-Store Installment
0
▶
Nominal minimal transaksi di Akulaku In-Store Installment
0
▶
Bunga untuk transaksi In-Store Installmet
0
▶
Tidak bisa transaksi di In-Store Installment
0
▶
Tidak bisa scan QR merchant pada saat transaksi menggunakan In-Store Installment
0
▶
Pembayaran tagihan In-Store Installment belum masuk sistem
0
▶
Request batalkan pesanan Hotel
0
▶
Tidak bisa belanja di Bukalapak pakai Akulaku
0
▶
Beli tiket XXI pakai limit Akulaku
0
▶
BL-Cara bayar uang muka
0
▶
Apakah bisa berbelanja paylater ditoko ofline akulaku
0
▶
Pengertian fitur Scan yang terdapat pada bagian Paylater
0
▶
Limit yang akan terpotong ketika saya menggunakan fitur (Scan)
0
▶
Apa itu fitur Barcode yang terdapat pada bagian Paylater?
0
▶
Tidak bisa menggunakan fitur Barcode? Terdapat notifikasi (Sorry, currently you cannot use this payment method. For further queries, please call Akulaku hotline at 1500920)
0
▶
Apa itu fitur QRIS KASPRO?
0
▶
Apa yang membedakan dengan fitur QRIS KASPRO dengan fitur Scan?
0
▶
Berasal darimana sumber nominal yang tertera pada fitur QRIS KASPRO?
0
▶
Jika fitur Scan dan QRIS KASPRO adalah sama, apa yang membedakan dari kedua fitur tersebut?
0
▶
Ada berapa pilihan tenor yang tersedia untuk fitur QRIS KASPRO?
0
▶
Berapa persen bunga yang ditagihkan untuk transaksi menggunakan fitur QRIS KASPRO?
0
▶
Berapa persen denda yang dikenakan apabila saya mengalami keterlambatan pembayaran?
0
▶
Jika saya melakukan TOP UP pada fitur QRIS KASPRO, apakah saldo KASPRO di aplikasi Akulaku saya akan bertambah?
0
▶
Apakah untuk saldo QRIS KASPRO yang akan diterima oleh setiap user setelah aktivasi sama?
0
▶
Berapa nominal maksimum pembayaran per pesanan dengan menggunakan fitur metode pembayaran QRIS KASPRO?
0
▶
Pembayaran di pegipegi.com gagal pakai Akulaku
0
▶
Cara aktifkan fitur QRIS
0
▶
Sudah booking hotel, pembayaran menggunakan Akulaku gagal
0
▶
Bertanya apakah bisa menggunakan QRIS paylater
0
▶
Tidak muncul metode Akulaku di Bukalapak
0
▶
Kendala Lazada Paylater tidak bisa digunakan
0
▶
Limit Akulaku Paylater tidak kembali setelah pembatalan pesanan
0
▶
Pengajuan limit kredit Lazada Paylater ditolak
0
▶
Cara pengajuan Akulaku PayLater
0
▶
Pengajuan retur produk Akulaku Paylater
0
▶
Penggunaan limit Openpay yang hanya bisa dipakai di beberapa merchant
0
▶
Status pembayaran QRIS masih Dalam Proses
0
▶
Cara penggunaan layanan pembayaran offline
0
▶
Cara bayar tagihan Lazada Paylater
0
▶
Kendala penggunaan layanan scan kode offline
0
▶
Tidak bisa lakukan transaksi-diminta pembayaran fullpayment
0
▶
Lazada Paylater/Rejected By Akulaku
0
▶
Kendala tidak bisa pembayaran Blibli pakai Akulaku Paylater
0
▶
Cara belanja di Shopee pakai Akulaku Paylater
0
▶
Tidak ada metode pembayaran Akulaku di aplikasi Shopee
0
▶
Pemesanan hotel menggunakan QRIS
0
▶
Pengertian Akulaku
0
▶
Lama masa perlindungan
0
▶
Cakupan perlindungan
0
▶
Jenis resiko perlindungan
0
▶
Jenis resiko yang tidak masuk perlindungan
0
▶
Manfaat perlindungan
0
▶
Harga premi perlindungan
0
▶
Jaminan perlindungan untuk produk senilai Rp30.000.000
0
▶
Pihak rekanan kerja sama
0
▶
Cara klaim asuransi
0
▶
Rincian tagihan lazada paylater
0
▶
Akun Lazada Paylater dibekukan
0
▶
Lazada Paylater / Akun disalahgunakan, permintaan kode pembayaran
0
▶
Cara beli pulsa pakai limit Akulaku Paylater
0
▶
Cara mencairkan limit Akulaku Paylater
0
▶
Lazada Paylater - Tidak bisa pembayaran karena kendala login
"""

In [29]:
lines = [x.strip() for x in text.split("\n") if x.strip() not in ['▶', '0', '']]
afi_cat = pd.DataFrame(lines, columns=['label_category'])
afi_cat

                                        label_category
0                  Alfacart - Pembayaran tidak sinkron
1               Alfacart - Status cancel tidak sinkron
2                  Apakah bisa belanja di toko offline
3               Bhinneka - Status cancel tidak sinkron
4                     BL - Status cancel tidak sinkron
..                                                 ...
120                     Akun Lazada Paylater dibekukan
121  Lazada Paylater / Akun disalahgunakan, permint...
122       Cara beli pulsa pakai limit Akulaku Paylater
123             Cara mencairkan limit Akulaku Paylater
124  Lazada Paylater - Tidak bisa pembayaran karena...

[125 rows x 1 columns]

In [30]:
lop = pd.read_csv('raw_data/llm_qc.csv')
lop

,date,validator,scenario_category,sub_category,detail_category,Result,LLM_dislike_reason,text_mandarin
0,1/22/2026,Aulia,Angsuran dan Pinjaman,Dana pinjaman tidak sesuai,Pinjaman,Like,NaN,NaN
1,1/22/2026,Aulia,Angsuran dan Pinjaman,Dana pinjaman tidak sesuai,Pinjaman,Like,NaN,NaN
2,1/22/2026,Aulia,Angsuran dan Pinjaman,Dana pinjaman tidak sesuai,Pinjaman,Dislike,jawaban LLM tidak sesuai dengan FAQ,NaN
3,1/22/2026,Aulia,Angsuran dan Pinjaman,Dana pinjaman tidak sesuai,Pinjaman,Like,NaN,NaN
4,1/22/2026,Aulia,Angsuran dan Pinjaman,Dana pinjaman tidak sesuai,Pinjaman,Like,NaN,NaN
...,...,...,...,...,...,...,...,...
2119,3/4/2026,Aulia,Akulaku paylater,Bertanya apakah bisa menggunakan QRIS paylater,Akulaku paylater,NaN,NaN,NaN
2120,3/4/2026,Aulia,Akulaku paylater,Bertanya apakah bisa menggunakan QRIS paylater,Akulaku paylater,NaN,NaN,NaN
2121,3/4/2026,Aulia,Akulaku paylater,Bertanya apakah bisa menggunakan QRIS paylater,Akulaku paylater,NaN,NaN,NaN
2122,3/4/2026,Aulia,Akulaku paylater,Bertanya apakah bisa menggunakan QRIS paylater,Akulaku paylater,NaN,NaN,NaN
2123,3/4/2026,Aulia,Akulaku paylater,Bertanya apakah bisa menggunakan QRIS paylater,Akulaku paylater,NaN,NaN,NaN

In [36]:
# lowering all in lop
lop = lop.applymap(lambda s: s.lower() if type(s) == str else s)

#lowering all in afi_cat and removing any additional spaces in case
afi_cat = afi_cat.applymap(lambda s: s.lower() if type(s) == str else s)
afi_cat = afi_cat.applymap(lambda s: s.strip() if type(s) == str else s)

C:\Users\ozy.prazuganda\AppData\Local\Temp\ipykernel_5456\3669293226.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  lop = lop.applymap(lambda s: s.lower() if type(s) == str else s)
C:\Users\ozy.prazuganda\AppData\Local\Temp\ipykernel_5456\3669293226.py:5: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  afi_cat = afi_cat.applymap(lambda s: s.lower() if type(s) == str else s)
C:\Users\ozy.prazuganda\AppData\Local\Temp\ipykernel_5456\3669293226.py:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  afi_cat = afi_cat.applymap(lambda s: s.strip() if type(s) == str else s)

In [39]:
sub_category = pd.DataFrame(lop['sub_category'].unique(), columns=['sub_category'])
sub_category

sub_category.merge(afi_cat, left_on='sub_category', right_on='label_category', how='right')

,sub_category,label_category
0,alfacart - pembayaran tidak sinkron,alfacart - pembayaran tidak sinkron
1,NaN,alfacart - status cancel tidak sinkron
2,apakah bisa belanja di toko offline,apakah bisa belanja di toko offline
3,bhinneka - status cancel tidak sinkron,bhinneka - status cancel tidak sinkron
4,NaN,bl - status cancel tidak sinkron
...,...,...
120,NaN,akun lazada paylater dibekukan
121,"lazada paylater / akun disalahgunakan, permint...","lazada paylater / akun disalahgunakan, permint..."
122,NaN,cara beli pulsa pakai limit akulaku paylater
123,NaN,cara mencairkan limit akulaku paylater
124,NaN,lazada paylater - tidak bisa pembayaran karena...