In [1]:
import gspread
import pandas as pd
from google.oauth2.service_account import Credentials

## Pipeline A

In [2]:
SERVICE_ACCOUNT_FILE = '../../key/credentials.json'
SCOPES = ['https://www.googleapis.com/auth/spreadsheets',
          'https://www.googleapis.com/auth/drive']

creds = Credentials.from_service_account_file(SERVICE_ACCOUNT_FILE, scopes=SCOPES)
client = gspread.authorize(creds)

sheet = client.open("Chatbot Ops Report").worksheet("Raw Data Robot Succes ratio")
data = sheet.get_all_values()

df = pd.DataFrame(data[1:], columns=data[0])
df.to_csv('../../raw_data/robot_success_ratio.csv', index=False)

In [3]:
df_clean = (
    df.copy()
    .rename(columns=lambda c: c.encode('ascii', 'ignore').decode('ascii').strip())
    .replace('', pd.NA)
    .dropna(subset=['Connected to robot'], how='all')
)

df_clean

,Connected to robot,Number of exit queues,Transfer amount to CS,Total handle robot,Robot handle ratio,Robot actual completion ratio,Robot Success ratio,Date
0,321,25,182,139,43.30%,35.51%,31.00%,20-May-2022
1,1521,80,902,619,40.70%,35.44%,34.00%,21-May-2022
2,2728,100,1570,1158,42.45%,38.78%,37.00%,22-May-2022
3,4424,276,2568,1856,41.95%,35.71%,33.00%,23-May-2022
4,6405,540,3378,3027,47.26%,38.83%,36.00%,24-May-2022
...,...,...,...,...,...,...,...,...
1436,11976,4,4527,7449,62.20%,62.17%,62.17%,25-Apr-2026
1437,10477,3,3873,6604,63.03%,63.00%,63.00%,26-Apr-2026
1438,11444,0,4384,7060,61.69%,61.69%,61.69%,27-Apr-2026
1439,11730,0,4447,7283,62.09%,62.09%,62.09%,28-Apr-2026
1440,11011,0,4115,6896,62.63%,62.63%,62.63%,29-Apr-2026

In [4]:
# Removing last row
df_clean = df_clean[:-1]

In [5]:
df_clean['Date'] = pd.to_datetime(df_clean['Date'], format='%d-%b-%Y', errors='coerce')

clean_list = ['Robot handle ratio',
              'Robot actual completion ratio', 
              'Robot Success ratio']

for col in clean_list:
    df_clean[col] = df_clean[col].str.replace('%','',regex=False).astype(float)

df_clean

C:\Users\ozy.prazuganda\AppData\Local\Temp\ipykernel_5736\3431615758.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['Date'] = pd.to_datetime(df_clean['Date'], format='%d-%b-%Y', errors='coerce')
C:\Users\ozy.prazuganda\AppData\Local\Temp\ipykernel_5736\3431615758.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean[col] = df_clean[col].str.replace('%','',regex=False).astype(float)
C:\Users\ozy.prazuganda\AppData\Local\Temp\ipykernel_5736\3431615758.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean[col] = df_clean[col].str.replace('%','',regex=False).astype(float)
C:\Users\ozy.prazuganda\AppData\Local\Temp\ipykernel_5736\3431615758.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean[col] = df_clean[col].str.replace('%','',regex=False).astype(float)

,Connected to robot,Number of exit queues,Transfer amount to CS,Total handle robot,Robot handle ratio,Robot actual completion ratio,Robot Success ratio,Date
0,321,25,182,139,43.30,35.51,31.00,2022-05-20
1,1521,80,902,619,40.70,35.44,34.00,2022-05-21
2,2728,100,1570,1158,42.45,38.78,37.00,2022-05-22
3,4424,276,2568,1856,41.95,35.71,33.00,2022-05-23
4,6405,540,3378,3027,47.26,38.83,36.00,2022-05-24
...,...,...,...,...,...,...,...,...
1435,11250,3,4199,7051,62.68,62.65,62.65,2026-04-24
1436,11976,4,4527,7449,62.20,62.17,62.17,2026-04-25
1437,10477,3,3873,6604,63.03,63.00,63.00,2026-04-26
1438,11444,0,4384,7060,61.69,61.69,61.69,2026-04-27
1439,11730,0,4447,7283,62.09,62.09,62.09,2026-04-28

In [6]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1440 entries, 0 to 1439
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Connected to robot             1440 non-null   object
 1   Number of exit queues          1440 non-null   object
 2   Transfer amount to CS          1440 non-null   object
 3   Total handle robot             1440 non-null   object
 4   Robot handle ratio             1440 non-null   float64
 5   Robot actual completion ratio  1440 non-null   float64
 6   Robot Success ratio            1440 non-null   float64
 7   Date                           1440 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(3), object(4)
memory usage: 90.1+ KB

## Pipeline B

In [7]:
df_clean.to_csv('../../dataset_kula/success_ratio.csv')