In [2]:
import gspread
import pandas as pd
from google.oauth2.service_account import Credentials

### File A

In [ ]:
SERVICE_ACCOUNT_FILE = '../key/Credentials.json'
SCOPES = ['https://www.googleapis.com/auth/spreadsheets',
          'https://www.googleapis.com/auth/drive']

creds = Credentials.from_service_account_file(SERVICE_ACCOUNT_FILE, scopes=SCOPES)
client = gspread.authorize(creds)

sheet = client.open("sample_3-1-robot").worksheet('sample 质检')
data = sheet.get_all_values()

df = pd.DataFrame(data[1:], columns=data[0])
df.to_csv('../dataset_wellbore/sample_3-1-robot2.csv')

:

In [12]:
df

,,Rating Guides,"1 Jawaban tidak sesuai, tidak natural, dan opsi yang diberikan tidak sesuai",,,,"4 Jawaban sesuai dan tidak ada opsi yang diberikan, namun respon terdengar tidak natural",,,,,
0,,,"2 Jawaban tidak sesuai, tetapi opsi yang diber...",,,,"5 Jawaban sesuai dan terdengar natural, serta ...",,,,,
1,,,"3 Jawaban dan opsi sudah sesuai, tetapi respon...",,,,,,,,,
2,Data_Date_Range,Checking_Date,Model 机器人,Chat ID,Validator 审核员,Result 结果,Overall Rating 评分,Pain Point 痛点,Supposed Response,,,
3,May 19 - May 26,05/29/2026,3-1-robot,2-117478928-3-1_1779268396,Aul,Correct Response,3,Kula langsung memberikan opsi dan jawaban dari...,,,,
4,May 19 - May 26,05/29/2026,3-1-robot,2-122276817-3-1_1779512825,Aul,Correct Response,3,Kula langsung memberikan opsi dan jawaban dari...,,1,,
...,...,...,...,...,...,...,...,...,...,...,...,...
2287,,07/10/2026,3-1-robot2,2-2044131443-3-1_1783329278,Reza,Correct Response,5,,,,,
2288,,07/10/2026,3-1-robot2,2-20597810-3-1_1783295712,Reza,Correct Response,5,,,,,
2289,,07/10/2026,3-1-robot2,2-4266520-3-1_1783436331,Reza,Correct Response,5,,,,,
2290,,07/10/2026,3-1-robot2,2-2060208710-3-1_1783303007,Reza,Correct Response,5,,,,,
2291,,07/10/2026,3-1-robot2,2-2061247921-3-1_1783311307,Reza,Correct Response,5,,,,,

### File B

In [14]:
df_high_risk = pd.read_csv('../dataset_wellbore/high_risk_20260701.csv')
df_high_risk

,行号,msg_text,old_model,new_model,人工打标结果,备注,打标人,打标时间,LLM打标结果,LLM模型,LLM打标时间,状态,old_model_vs人工,new_model_vs人工,old_model_vsLLM,new_model_vsLLM
0,2,udah lah klu emang g dapet dah gpp cape² sy un...,keluhan di tempat,normal,"{""value"": ""normal""}",Tidak ada kata HC yang disebutkan customer nam...,Muhammad Reza Mauladi,2026-07-03 07:58:51,ketidakpuasan,deepseek-v3,2026-07-02 10:33:31,labeled,否,是,否,否
1,3,sya viralkan sjh ini aplikasi biar tdak ad yan...,keluhan,ulasan buruk,"{""value"": ""keluhan""}",NaN,Muhammad Reza Mauladi,2026-07-03 07:58:51,ulasan buruk,deepseek-v3,2026-07-02 10:33:35,labeled,是,否,否,是
2,4,sy bntu viral kn biar tdak ad yang pakai,keluhan,ulasan buruk,"{""value"": ""keluhan""}",NaN,Muhammad Reza Mauladi,2026-07-03 07:58:51,ulasan buruk,deepseek-v3,2026-07-02 10:33:39,labeled,是,否,否,是
3,5,sy viralkan ini aplikasi biar tdak ad yng paka...,keluhan,ulasan buruk,"{""value"": ""keluhan""}",NaN,Muhammad Reza Mauladi,2026-07-03 07:58:51,keluhan,deepseek-v3,2026-07-02 10:33:43,labeled,是,否,是,否
4,6,Akan saya viral ini akulaku,keluhan,ulasan buruk,"{""value"": ""keluhan""}",NaN,Muhammad Reza Mauladi,2026-07-03 07:58:51,keluhan,deepseek-v3,2026-07-02 10:33:47,labeled,是,否,是,否
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1992,2094,biar viral,keluhan,ulasan buruk,"{""value"": ""keluhan""}",NaN,Aulia Az-Zahra,2026-07-10 02:17:28,normal,deepseek-v3,2026-07-02 13:09:49,labeled,是,否,否,否
1993,2095,mau saya viralkan ini akulaku,keluhan,ulasan buruk,"{""value"": ""keluhan""}",NaN,Aulia Az-Zahra,2026-07-10 02:17:28,keluhan di tempat,deepseek-v3,2026-07-02 13:09:56,labeled,是,否,否,否
1994,2096,klau tidak di acc saya viralkan toko nya dan a...,keluhan,normal,"{""value"": ""keluhan""}",NaN,Aulia Az-Zahra,2026-07-10 02:17:28,keluhan,deepseek-v3,2026-07-02 13:10:00,labeled,是,否,是,否
1995,2097,UNTUK POSTINGAN DI MEDIA SOSIAL SUDAH SAYA POS...,keluhan,ulasan buruk,"{""value"": ""keluhan""}",NaN,Aulia Az-Zahra,2026-07-10 02:17:28,normal,deepseek-v3,2026-07-02 13:10:04,labeled,是,否,否,否
1996,2098,UNTUK LAMAN DI MEDIA SOSIAL SUDAH SAYA POST IN...,keluhan,normal,"{""value"": ""keluhan""}",NaN,Aulia Az-Zahra,2026-07-10 02:17:28,normal,deepseek-v3,2026-07-02 13:10:10,labeled,是,否,否,是