In [3]:
import pandas as pd

In [4]:
df_task = pd.read_csv(
    '../dataset_wellbore/包含 1500920的话术 - 工作表1.csv'
)

df_dataset = pd.read_csv(
    '../dataset_wellbore/NEW Akulaku - AI Kula Scene Classification (2025) - NEW 12.14.csv'
)

In [5]:
df_task

,code,Background_Detail_ID,ID_Example,New_Answer,是否修改,新的code（code不变不需要填写）,Validator,Test Pass?,Error Note
0,1-11-47-271,[Global Buy] Produk hilang di jasa kirim,Bagaimana jika produk Global Buy hilang di jas...,NaN,是 Yes,NaN,Hamni,是 Yes,NaN
1,1-11-48-864,Produk hilang di jasa kirim,Bagaimana jika produk Merchant Online hilang d...,NaN,是 Yes,NaN,Hamni,是 Yes,NaN
2,1-11-49-865,Produk hilang di jasa kirim produk official,Bagaimana jika produk Produk Official Store hi...,NaN,是 Yes,NaN,Hamni,是 Yes,NaN
3,1-14-56-867,Transaksi berhasil namun belum diterima produk...,Bagaimana jika status pesanan Produk Official ...,NaN,是 Yes,NaN,Hamni,是 Yes,NaN
4,1-24-68-771,"Kenapa sudah melakukan pembayaran Dp, pesanan ...",Kenapa DP sudah bayar kok barang tidak jadi di...,NaN,是 Yes,NaN,Hamni,是 Yes,NaN
...,...,...,...,...,...,...,...,...,...
236,872-948-1043-759,Pelunasan semua tagihan Dana Cicil,Bagaimana metode pembayaran jika ingin melunas...,NaN,NaN,NaN,NaN,NaN,NaN
237,872-954-1049-804,"Barang sudah diretur, tagihan muncul",Kenapa tagihan masih muncul padahal sudah pros...,NaN,NaN,NaN,NaN,NaN,NaN
238,872-955-1050-806,Tagihan PDAM masih muncul,"Kenapa tagihan PDAM masih muncul, padahal suda...",NaN,NaN,NaN,NaN,NaN,NaN
239,872-958-1053-828,"Pembayaran gagal, saldo rekening terpotong",Apa yang harus dilakukan jika menemukan kendal...,NaN,NaN,NaN,NaN,NaN,NaN
240,872-962-1057-879,Tidak muncul Virtual Account tagihan Pinjaman,Tolong dibantu saya mau melunasi pinjaman Dana...,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df_dataset

,Unnamed: 0,No,Create Time,Classification Business,FAQ Status,OLD Code,New-Code,一级分类\nKategori 1 (CN),分类（英）\nKategori 1 (EN),分类（印尼）\nKategori 1 (ID),...,NEW - ANSWER,Wordcounter,回复2,需求,ID\n(P1 Plan: Poin 2),Explanation,Update / Revision FAQ Date,Add Screenshot/GIFT,Operator,Update & Testing
0,无更新,1,12/1/2022,ASI,Online,130101,794-795-809-117,ETC,ETC,Lain-Lain,...,Mohon maaf untuk jenis permasalahan ini memerl...,NaN,转人工// alihkan CS,NaN,transferred to CS (转人工）,Old 10.13,24 July 2024,NaN,NaN,NaN
1,无更新,2,12/1/2022,ASI,Online,180101,1210-1211-1257-118,退款,Refund,Refund,...,Jika Kakak sudah sukses melakukan pembayaran n...,NaN,已有卡片 【申请退款】//\nsudah ada klasifikasi ttg refund,NaN,finished by chatbot (机器人解决）,Old 10.13,2 November 2023,NaN,NaN,NaN
2,无更新,3,12/1/2022,ASI,Online,31001,597-598-609-119,保险,Insurance,Asuransi,...,Kakak bisa melakukan pengecekan terlebih dahul...,NaN,ASI,NaN,finished by chatbot (机器人解决）,Old 10.13,2 November 2023,NaN,NaN,NaN
3,无更新,4,12/1/2022,ASI,Online,131601,1-2-28-120,物流,Logistics,Logistik,...,Jika pihak penjual meminta biaya tambahan ongk...,NaN,已有卡片 【物流轨迹卡】// sudah ada klasifikasi ttg pengi...,NaN,finished by chatbot (机器人解决）,Old 10.13,2 November 2023,NaN,NaN,NaN
4,无更新,5,12/1/2022,AFI,Online,70401,738-739-758-121,帐户安全,Account security,Keamanan Akun,...,Kula bantu informasikan bahwa setelah Kakak me...,NaN,AFI,加安全中心卡片【临时冻结，永久冻结】,finished by chatbot (机器人解决）,Old 10.13,22 April 2025,SS & GIFT,Hamni,Done
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
946,NaN,947,NaN,AFI,Online,NaN,1321-1912-1913-1261,SLIK,SLIK,SLIK,...,NaN,NaN,NaN,NaN,finished by chatbot (机器人解决）,NaN,NaN,NaN,NaN,NaN
947,NaN,948,NaN,AFI,Online,NaN,1321-1914-1915-1262,SLIK,SLIK,SLIK,...,NaN,NaN,NaN,NaN,finished by chatbot (机器人解决）,NaN,NaN,NaN,NaN,NaN
948,NaN,949,NaN,ASI,Online,NaN,1321-1916-1917-1264,SLIK,SLIK,SLIK,...,NaN,NaN,NaN,NaN,finished by chatbot (机器人解决）,NaN,NaN,NaN,NaN,NaN
949,NaN,950,NaN,ASI,Online,NaN,1321-1918-1919-1265,SLIK,SLIK,SLIK,...,NaN,NaN,NaN,NaN,finished by chatbot (机器人解决）,NaN,NaN,NaN,NaN,NaN
950,NaN,951,NaN,ASI,Online,NaN,1321-1920-1921-1266,SLIK,SLIK,SLIK,...,NaN,NaN,NaN,NaN,finished by chatbot (机器人解决）,NaN,NaN,NaN,NaN,NaN

In [14]:
df_dataset[['New-Code','ID\n(P1 Plan: Poin 2)', 'NEW - ANSWER']]

,New-Code,ID\n(P1 Plan: Poin 2),NEW - ANSWER
0,794-795-809-117,transferred to CS (转人工）,Mohon maaf untuk jenis permasalahan ini memerl...
1,1210-1211-1257-118,finished by chatbot (机器人解决）,Jika Kakak sudah sukses melakukan pembayaran n...
2,597-598-609-119,finished by chatbot (机器人解决）,Kakak bisa melakukan pengecekan terlebih dahul...
3,1-2-28-120,finished by chatbot (机器人解决）,Jika pihak penjual meminta biaya tambahan ongk...
4,738-739-758-121,finished by chatbot (机器人解决）,Kula bantu informasikan bahwa setelah Kakak me...
...,...,...,...
946,1321-1912-1913-1261,finished by chatbot (机器人解决）,NaN
947,1321-1914-1915-1262,finished by chatbot (机器人解决）,NaN
948,1321-1916-1917-1264,finished by chatbot (机器人解决）,NaN
949,1321-1918-1919-1265,finished by chatbot (机器人解决）,NaN
950,1321-1920-1921-1266,finished by chatbot (机器人解决）,NaN