In [1]:
import pandas as pd

In [2]:
df_task = pd.read_csv(
    '../dataset_wellbore/包含 1500920的话术 - 工作表1.csv'
)

df_dataset = pd.read_csv(
    '../dataset_wellbore/NEW Akulaku - AI Kula Scene Classification (2025) - NEW 12.14.csv'
)

In [15]:
df_dataset

,Unnamed: 0,No,Create Time,Classification Business,FAQ Status,OLD Code,New-Code,一级分类\nKategori 1 (CN),分类（英）\nKategori 1 (EN),分类（印尼）\nKategori 1 (ID),...,NEW - ANSWER,Wordcounter,回复2,需求,ID\n(P1 Plan: Poin 2),Explanation,Update / Revision FAQ Date,Add Screenshot/GIFT,Operator,Update & Testing
0,无更新,1,12/1/2022,asi,online,130101,794-795-809-117,etc,etc,lain-lain,...,mohon maaf untuk jenis permasalahan ini memerl...,NaN,转人工// alihkan cs,NaN,transferred to cs (转人工）,old 10.13,24 july 2024,NaN,NaN,NaN
1,无更新,2,12/1/2022,asi,online,180101,1210-1211-1257-118,退款,refund,refund,...,jika kakak sudah sukses melakukan pembayaran n...,NaN,已有卡片 【申请退款】//\nsudah ada klasifikasi ttg refund,NaN,finished by chatbot (机器人解决）,old 10.13,2 november 2023,NaN,NaN,NaN
2,无更新,3,12/1/2022,asi,online,31001,597-598-609-119,保险,insurance,asuransi,...,kakak bisa melakukan pengecekan terlebih dahul...,NaN,asi,NaN,finished by chatbot (机器人解决）,old 10.13,2 november 2023,NaN,NaN,NaN
3,无更新,4,12/1/2022,asi,online,131601,1-2-28-120,物流,logistics,logistik,...,jika pihak penjual meminta biaya tambahan ongk...,NaN,已有卡片 【物流轨迹卡】// sudah ada klasifikasi ttg pengi...,NaN,finished by chatbot (机器人解决）,old 10.13,2 november 2023,NaN,NaN,NaN
4,无更新,5,12/1/2022,afi,online,70401,738-739-758-121,帐户安全,account security,keamanan akun,...,kula bantu informasikan bahwa setelah kakak me...,NaN,afi,加安全中心卡片【临时冻结，永久冻结】,finished by chatbot (机器人解决）,old 10.13,22 april 2025,ss & gift,hamni,done
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
946,NaN,947,NaN,afi,online,NaN,1321-1912-1913-1261,slik,slik,slik,...,NaN,NaN,NaN,NaN,finished by chatbot (机器人解决）,NaN,NaN,NaN,NaN,NaN
947,NaN,948,NaN,afi,online,NaN,1321-1914-1915-1262,slik,slik,slik,...,NaN,NaN,NaN,NaN,finished by chatbot (机器人解决）,NaN,NaN,NaN,NaN,NaN
948,NaN,949,NaN,asi,online,NaN,1321-1916-1917-1264,slik,slik,slik,...,NaN,NaN,NaN,NaN,finished by chatbot (机器人解决）,NaN,NaN,NaN,NaN,NaN
949,NaN,950,NaN,asi,online,NaN,1321-1918-1919-1265,slik,slik,slik,...,NaN,NaN,NaN,NaN,finished by chatbot (机器人解决）,NaN,NaN,NaN,NaN,NaN
950,NaN,951,NaN,asi,online,NaN,1321-1920-1921-1266,slik,slik,slik,...,NaN,NaN,NaN,NaN,finished by chatbot (机器人解决）,NaN,NaN,NaN,NaN,NaN

In [26]:
# Clean dataset
df_task = df_task.applymap(lambda x: x.strip().lower() if isinstance(x, str) else x)
df_dataset = df_dataset.applymap(lambda x: x.strip().lower() if isinstance(x, str) else x)

# clean columns names
df_dataset = df_dataset.applymap(lambda x: x.replace('\n', ' ').replace('\r', ' ') if isinstance(x, str) else x)

df_dataset.columns

C:\Users\ozy.prazuganda\AppData\Local\Temp\ipykernel_11476\4032588328.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_task = df_task.applymap(lambda x: x.strip().lower() if isinstance(x, str) else x)
C:\Users\ozy.prazuganda\AppData\Local\Temp\ipykernel_11476\4032588328.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_dataset = df_dataset.applymap(lambda x: x.strip().lower() if isinstance(x, str) else x)
C:\Users\ozy.prazuganda\AppData\Local\Temp\ipykernel_11476\4032588328.py:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_dataset = df_dataset.applymap(lambda x: x.replace('\n', ' ').replace('\r', ' ') if isinstance(x, str) else x)

Index(['Unnamed: 0', 'No', 'Create Time', 'Classification Business',
       'FAQ Status', 'OLD Code', 'New-Code', '一级分类\nKategori 1 (CN)',
       '分类（英）\nKategori 1 (EN)', '分类（印尼）\nKategori 1 (ID)',
       '二级分类（中文）--场景\nKategori 2 (CN)', '二级分类（英文）--场景\nKategori 2 (EN)',
       '二级分类（印尼语）--场景\nKategori 2 (ID)', '三级分类 \nKategori 3 (CN)',
       '三级分类（英文）--场景\nKategori 3 (EN)', '三级分类（印尼文）--场景\nKategori 3 (ID)',
       '场景描述- CN\nBackground detail- CN', '场景描述- EN\nBackground detail- EN',
       '场景描述- ID\nBackground detail- ID', '例子 \nCN\nExample',
       '例子 \nEN\nExample', '例子 \nID\nExample',
       '相似问题1-中文\nPertanyaan Serupa1-CN', '相似问题1-EN\nPertanyaan Serupa1-EN',
       '相似问题1-ID\nPertanyaan Serupa 1-ID', '相似问题2-中文\nPertanyaan Serupa2-CN',
       '相似问题2-EN\nPertanyaan Serupa2-EN', '相似问题2-ID\nPertanyaan Serupa 2-ID',
       '相似问题3-中文\nPertanyaan Serupa3-CN', '相似问题3-EN\nPertanyaan Serupa3-EN',
       '相似问题3-ID\nPertanyaan Serupa 3-ID', '相似问题4-中文\nPertanyaan Serupa4-CN',
       '相似问题4-EN\nPertanyaan Serupa4-EN', '相似问题4-ID\nPertanyaan Serupa 4-ID',
       '相似问题5-中文\nPertanyaan Serupa5-CN', '相似问题5-EN\nPertanyaan Serupa5-EN',
       '相似问题5-ID\nPertanyaan Serupa 5-ID', '相似问题5-ID\nPertanyaan Serupa 6-ID',
       '相似问题5-ID\nPertanyaan Serupa 7-ID', '相似问题5-ID\nPertanyaan Serupa 8-ID',
       '相似问题5-ID\nPertanyaan Serupa 9-ID', '相似问题5-ID\nPertanyaan Serupa 10-ID',
       '回复\nAnswer ', '回复\nEN\nAnswer ', '回复\nID\nAnswer ',
       '回复\nCN\nNEW - ANSWER', '回复\nEN\nNEW - ANSWER', 'NEW - ANSWER',
       'Wordcounter', '回复2', '需求', 'ID\n(P1 Plan: Poin 2)', 'Explanation',
       'Update / Revision  FAQ Date', 'Add Screenshot/GIFT', 'Operator',
       'Update & Testing'],
      dtype='object')

In [27]:
dataset_trimmed = df_dataset[['New-Code','ID\n(P1 Plan: Poin 2)', '回复\nID\nAnswer ', 'NEW - ANSWER']]
dataset_trimmed

,New-Code,ID\n(P1 Plan: Poin 2),回复\nID\nAnswer,NEW - ANSWER
0,794-795-809-117,transferred to cs (转人工）,"maaf, kula tidak mengerti apa yang anda maksud...",mohon maaf untuk jenis permasalahan ini memerl...
1,1210-1211-1257-118,finished by chatbot (机器人解决）,jika anda sudah sukses melakukan pembayaran na...,jika kakak sudah sukses melakukan pembayaran n...
2,597-598-609-119,finished by chatbot (机器人解决）,anda bisa melakukan pengecekan terlebih dahulu...,kakak bisa melakukan pengecekan terlebih dahul...
3,1-2-28-120,finished by chatbot (机器人解决）,jika pihak penjual meminta biaya tambahan ongk...,jika pihak penjual meminta biaya tambahan ongk...
4,738-739-758-121,finished by chatbot (机器人解决）,perlu diketahui bahwa setelah anda melakukan p...,kula bantu informasikan bahwa setelah kakak me...
...,...,...,...,...
946,1321-1912-1913-1261,finished by chatbot (机器人解决）,kula bantu informasikan bahwa waktu pembaruan ...,NaN
947,1321-1914-1915-1262,finished by chatbot (机器人解决）,kula bantu informasikan bahwa nominal tagihan ...,NaN
948,1321-1916-1917-1264,finished by chatbot (机器人解决）,kula informasikan bahwa akulaku bekerjasama de...,NaN
949,1321-1918-1919-1265,finished by chatbot (机器人解决）,kula bantu informasikan bahwa waktu pembaruan ...,NaN
950,1321-1920-1921-1266,finished by chatbot (机器人解决）,kula bantu informasikan bahwa nominal tagihan ...,NaN

In [28]:
df_task.merge(dataset_trimmed, how='left', left_on='code', right_on='New-Code').to_csv('../dataset_wellbore/result_FAQ_id_example.csv', index=False)