In [1]:
import gspread
import pandas as pd
from google.oauth2.service_account import Credentials

## Pipeline A

In [20]:
SERVICE_ACCOUNT_FILE = '../../key/credentials.json'
SCOPES = ['https://www.googleapis.com/auth/spreadsheets',
          'https://www.googleapis.com/auth/drive']

creds = Credentials.from_service_account_file(SERVICE_ACCOUNT_FILE, scopes=SCOPES)
client = gspread.authorize(creds)

sheet = client.open('LLM Kula').worksheet('data_sheet')
data = sheet.get_all_values()

df = pd.DataFrame(data[2:], columns=data[1])

In [21]:
df

,date,validator,scenario_category,sub_category,detail_category,mode,chat_id,sequence,eSimCSE,LLM,eSimCSE_dislike_reason,LLM_dislike_reason
0,1/6/2026,Reza,Logistik,sistem dan status logistik menunjukkan bahwa b...,Merchant Online,putar_ulang,2-11790357-3-1,1,Like,Dislike,,
1,1/6/2026,Reza,Logistik,sistem dan status logistik menunjukkan bahwa b...,Merchant Online,putar_ulang,2-11790357-3-1,2,Dislike,Like,tidak ada jawaban langsung kepada user,
2,1/6/2026,Reza,Logistik,sistem dan status logistik menunjukkan bahwa b...,Merchant Online,putar_ulang,2-2052378674-3-1,1,Dislike,Like,tidak sesuai FAQ,
3,1/6/2026,Reza,Logistik,sistem dan status logistik menunjukkan bahwa b...,Merchant Online,putar_ulang,2-2052378674-3-1,2,Like,Dislike,,tidak menjawab pertanyaan user
4,1/6/2026,Reza,Logistik,sistem dan status logistik menunjukkan bahwa b...,Merchant Online,putar_ulang,2-2052378674-3-1,4,Dislike,Like,robot masih menanyakan kendala user,
...,...,...,...,...,...,...,...,...,...,...,...,...
86,1/7/2026,Reza,Logistik,tidak ada nomor resi,Merchant Online,putar_ulang,2-17666781-3-1,5,Dislike,Like,tidak ada jawaban,
87,1/7/2026,Reza,Logistik,"status order receive, tapi pesanan cust belom ...",global buy,chat_bebas,N/A,1,Like,Like,,
88,1/7/2026,Reza,Logistik,"status order receive, tapi pesanan cust belom ...",global buy,chat_bebas,N/A,2,Like,Like,,
89,1/7/2026,Reza,Logistik,"status order receive, tapi pesanan cust belom ...",global buy,chat_bebas,N/A,3,Dislike,Like,tidak ada empati dan menjawab user,
90,1/7/2026,Reza,Logistik,"status order receive, tapi pesanan cust belom ...",global buy,chat_bebas,N/A,4,Dislike,Like,jawaban tidak sesuai,

In [25]:
# copy the main df
df_clean = df.copy()

# change columns names into all lowercase
df_clean.columns = df_clean.columns.str.lower()

# date data type
df_clean['date'] = pd.to_datetime(
    df_clean['date']
)

# categorical data type
categorical_cols = [
    'validator', 'scenario_category', 'sub_category', 'detail_category', 'mode', 'esimcse', 'llm'
]

for col in categorical_cols:
    if col in df_clean.columns:
        df_clean[col] = df_clean[col].astype('category')

# numeric data type
df_clean['sequence'] = df_clean['sequence'].replace('', 0).astype(int)

# the data
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91 entries, 0 to 90
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   date                    91 non-null     datetime64[ns]
 1   validator               91 non-null     category
 2   scenario_category       91 non-null     category
 3   sub_category            91 non-null     category
 4   detail_category         91 non-null     category
 5   mode                    91 non-null     category
 6   chat_id                 91 non-null     object
 7   sequence                91 non-null     int64
 8   esimcse                 91 non-null     category
 9   llm                     91 non-null     category
 10  esimcse_dislike_reason  91 non-null     object
 11  llm_dislike_reason      91 non-null     object
dtypes: category(7), datetime64[ns](1), int64(1), object(3)
memory usage: 5.6+ KB

In [26]:
df_clean

,date,validator,scenario_category,sub_category,detail_category,mode,chat_id,sequence,esimcse,llm,esimcse_dislike_reason,llm_dislike_reason
0,2026-01-06,Reza,Logistik,sistem dan status logistik menunjukkan bahwa b...,Merchant Online,putar_ulang,2-11790357-3-1,1,Like,Dislike,,
1,2026-01-06,Reza,Logistik,sistem dan status logistik menunjukkan bahwa b...,Merchant Online,putar_ulang,2-11790357-3-1,2,Dislike,Like,tidak ada jawaban langsung kepada user,
2,2026-01-06,Reza,Logistik,sistem dan status logistik menunjukkan bahwa b...,Merchant Online,putar_ulang,2-2052378674-3-1,1,Dislike,Like,tidak sesuai FAQ,
3,2026-01-06,Reza,Logistik,sistem dan status logistik menunjukkan bahwa b...,Merchant Online,putar_ulang,2-2052378674-3-1,2,Like,Dislike,,tidak menjawab pertanyaan user
4,2026-01-06,Reza,Logistik,sistem dan status logistik menunjukkan bahwa b...,Merchant Online,putar_ulang,2-2052378674-3-1,4,Dislike,Like,robot masih menanyakan kendala user,
...,...,...,...,...,...,...,...,...,...,...,...,...
86,2026-01-07,Reza,Logistik,tidak ada nomor resi,Merchant Online,putar_ulang,2-17666781-3-1,5,Dislike,Like,tidak ada jawaban,
87,2026-01-07,Reza,Logistik,"status order receive, tapi pesanan cust belom ...",global buy,chat_bebas,N/A,1,Like,Like,,
88,2026-01-07,Reza,Logistik,"status order receive, tapi pesanan cust belom ...",global buy,chat_bebas,N/A,2,Like,Like,,
89,2026-01-07,Reza,Logistik,"status order receive, tapi pesanan cust belom ...",global buy,chat_bebas,N/A,3,Dislike,Like,tidak ada empati dan menjawab user,
90,2026-01-07,Reza,Logistik,"status order receive, tapi pesanan cust belom ...",global buy,chat_bebas,N/A,4,Dislike,Like,jawaban tidak sesuai,